stages:
  - build
  - coverage

full integration:
  stage: build
  script:
  - nvidia-smi
  - export CUDA_DEVICE_ORDER=PCI_BUS_ID
  - export CUDA_VISIBLE_DEVICES=0,1
  - python -m pip install --upgrade pip
  - pip uninstall -y torch torchvision
  - pip install -q -r requirements.txt
  - ./runtests.sh --net
  - echo "Done with runtests.sh --net"
  tags:
  - test

coverage test:
  stage: coverage
  only:
    - master
    - ci-stages
  script:
  - nvidia-smi
  - export CUDA_DEVICE_ORDER=PCI_BUS_ID
  - export CUDA_VISIBLE_DEVICES=0,1
  - python -m pip install --upgrade pip
  - pip uninstall -y torch torchvision
  - pip install -q -r requirements.txt
  - pip list
  - ./runtests.sh --coverage
  tags:
  - test
