coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 10
        base: parent
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    patch:
      default:
        target: auto
        # Allows PRs without tests, overall stats count
        threshold: 100
        base: auto
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null

# Disable comments on PR
comment: false
