name: CodeCoverage

on:
  push:
    branch:
      - master

jobs:
  coverage-py3:
    container:
      image: nvcr.io/nvidia/pytorch:19.10-py3
    runs-on: [self-hosted, linux, x64]
    steps:
    - uses: actions/checkout@v2
    - name: Install the dependencies
      run: |
        which python
        python -m pip install --upgrade pip --no-cache-dir
        python -m pip uninstall -y torch torchvision
        python -m pip install -q -r requirements.txt --no-cache-dir
        python -m pip list
    - name: Run unit tests report coverage
      run: |
        nvidia-smi
        export CUDA_DEVICE_ORDER=PCI_BUS_ID
        export CUDA_VISIBLE_DEVICES=0,1
        ./runtests.sh --coverage
        coverage xml
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        file: ./coverage.xml
